import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('muvimax-language');
    return saved || 'en';
  });

  useEffect(() => {
    localStorage.setItem('muvimax-language', language);
  }, [language]);

  const translations = {
    en: {
      appName: 'MUVIMAX',
      watchNow: 'Watch Now',
      moreInfo: 'More Info',
      continueWatching: 'Continue Watching',
      trendingNow: 'Trending Now',
      popularMovies: 'Popular Movies',
      newReleases: 'New Releases',
      topRated: 'Top Rated',
      recommendedForYou: 'Recommended For You',
      action: 'Action',
      comedy: 'Comedy',
      drama: 'Drama',
      horror: 'Horror',
      romance: 'Romance',
      thriller: 'Thriller',
      animation: 'Animation',
      sciFi: 'Sci-Fi',
      family: 'Family',
      recentlyAdded: 'Recently Added',
      search: 'Search',
      profile: 'Profile',
      settings: 'Settings',
      watchlist: 'Watchlist',
      favorites: 'Favorites',
      history: 'History',
      notifications: 'Notifications',
      loginRequired: 'Login Required',
      pleaseLogin: 'Please sign in to continue',
      signIn: 'Sign In',
      continueAsGuest: 'Continue as Guest',
      noResults: 'No results found',
      trySearch: 'Try searching for something else',
      loading: 'Loading...',
      error: 'Something went wrong',
      retry: 'Retry',
      emptyWatchlist: 'Your watchlist is empty',
      addMovies: 'Start adding movies to your watchlist',
      emptyFavorites: 'No favorites yet',
      startFavoriting: 'Start favoriting movies you love',
      emptyHistory: 'No watch history',
      startWatching: 'Start watching movies to build your history',
      emptyNotifications: 'No notifications',
      checkLater: 'Check back later for updates',
      darkMode: 'Dark Mode',
      lightMode: 'Light Mode',
      language: 'Language',
      video: 'Video',
      data: 'Data',
      privacy: 'Privacy',
      account: 'Account',
      logout: 'Logout',
      deleteData: 'Delete Local Data',
      playbackQuality: 'Playback Quality',
      autoplay: 'Autoplay',
      subtitles: 'Subtitles',
      playbackSpeed: 'Playback Speed',
      dataSaver: 'Data Saver Mode',
      autoQuality: 'Auto Video Quality',
      clearWatchHistory: 'Clear Watch History',
      clearSearchHistory: 'Clear Search History',
      clearContinueWatching: 'Clear Continue Watching',
      privacyPolicy: 'Privacy Policy',
      termsConditions: 'Terms & Conditions',
      about: 'About MUVIMAX',
      version: 'Version',
      joinDate: 'Joined',
      watchTime: 'Watch Time',
      moviesWatched: 'Movies Watched',
      favoriteGenres: 'Favorite Genres',
      totalRatings: 'Total Ratings',
      totalReviews: 'Total Reviews',
      watchlistCount: 'Watchlist Count',
      share: 'Share',
      addToWatchlist: 'Add to Watchlist',
      removeFromWatchlist: 'Remove from Watchlist',
      like: 'Like',
      unlike: 'Unlike',
      rate: 'Rate',
      writeReview: 'Write a Review',
      editReview: 'Edit Review',
      deleteReview: 'Delete Review',
      yourRating: 'Your Rating',
      averageRating: 'Average Rating',
      reviews: 'Reviews',
      similarMovies: 'Similar Movies',
      cast: 'Cast',
      genres: 'Genres',
      runtime: 'Runtime',
      year: 'Year',
      trailer: 'Trailer',
      play: 'Play',
      pause: 'Pause',
      fullscreen: 'Fullscreen',
      skipForward: 'Skip Forward',
      skipBackward: 'Skip Backward',
      pictureInPicture: 'Picture-in-Picture',
      quality: 'Quality',
      subtitlesOff: 'Subtitles Off',
      auto: 'Auto'
    },
    bn: {
      appName: 'MUVIMAX',
      watchNow: 'এখন দেখুন',
      moreInfo: 'আরও তথ্য',
      continueWatching: 'দেখা চালিয়ে যান',
      trendingNow: 'ট্রেন্ডিং',
      popularMovies: 'জনপ্রিয় সিনেমা',
      newReleases: 'নতুন রিলিজ',
      topRated: 'সর্বোচ্চ রেটেড',
      recommendedForYou: 'আপনার জন্য সুপারিশকৃত',
      action: 'অ্যাকশন',
      comedy: 'কমেডি',
      drama: 'নাটক',
      horror: 'হরর',
      romance: 'রোমান্স',
      thriller: 'থ্রিলার',
      animation: 'অ্যানিমেশন',
      sciFi: 'সাই-ফাই',
      family: 'পারিবারিক',
      recentlyAdded: 'সম্প্রতি যোগ হয়েছে',
      search: 'অনুসন্ধান',
      profile: 'প্রোফাইল',
      settings: 'সেটিংস',
      watchlist: 'ওয়াচলিস্ট',
      favorites: 'পছন্দের তালিকা',
      history: 'ইতিহাস',
      notifications: 'বিজ্ঞপ্তি',
      loginRequired: 'লগইন প্রয়োজন',
      pleaseLogin: 'চালিয়ে যেতে সাইন ইন করুন',
      signIn: 'সাইন ইন',
      continueAsGuest: 'অতিথি হিসেবে চালিয়ে যান',
      noResults: 'কোন ফলাফল পাওয়া যায়নি',
      trySearch: 'অন্য কিছু অনুসন্ধান করুন',
      loading: 'লোড হচ্ছে...',
      error: 'কিছু ভুল হয়েছে',
      retry: 'আবার চেষ্টা করুন',
      emptyWatchlist: 'আপনার ওয়াচলিস্ট খালি',
      addMovies: 'আপনার ওয়াচলিস্টে সিনেমা যোগ করুন',
      emptyFavorites: 'কোন পছন্দের সিনেমা নেই',
      startFavoriting: 'আপনার পছন্দের সিনেমা পছন্দের তালিকায় যোগ করুন',
      emptyHistory: 'কোন দেখার ইতিহাস নেই',
      startWatching: 'ইতিহাস তৈরি করতে সিনেমা দেখা শুরু করুন',
      emptyNotifications: 'কোন বিজ্ঞপ্তি নেই',
      checkLater: 'আপডেটের জন্য পরে চেক করুন',
      darkMode: 'ডার্ক মোড',
      lightMode: 'লাইট মোড',
      language: 'ভাষা',
      video: 'ভিডিও',
      data: 'ডেটা',
      privacy: 'গোপনীয়তা',
      account: 'অ্যাকাউন্ট',
      logout: 'লগআউট',
      deleteData: 'স্থানীয় ডেটা মুছুন',
      playbackQuality: 'প্লেব্যাক মান',
      autoplay: 'অটোপ্লে',
      subtitles: 'সাবটাইটেল',
      playbackSpeed: 'প্লেব্যাক গতি',
      dataSaver: 'ডেটা সেভার মোড',
      autoQuality: 'স্বয়ংক্রিয় ভিডিও মান',
      clearWatchHistory: 'দেখার ইতিহাস মুছুন',
      clearSearchHistory: 'অনুসন্ধান ইতিহাস মুছুন',
      clearContinueWatching: 'চলমান দেখা মুছুন',
      privacyPolicy: 'গোপনীয়তা নীতি',
      termsConditions: 'শর্তাবলী',
      about: 'MUVIMAX সম্পর্কে',
      version: 'সংস্করণ',
      joinDate: 'যোগদান',
      watchTime: 'দেখার সময়',
      moviesWatched: 'দেখা সিনেমা',
      favoriteGenres: 'পছন্দের ধরণ',
      totalRatings: 'মোট রেটিং',
      totalReviews: 'মোট রিভিউ',
      watchlistCount: 'ওয়াচলিস্ট সংখ্যা',
      share: 'শেয়ার',
      addToWatchlist: 'ওয়াচলিস্টে যোগ করুন',
      removeFromWatchlist: 'ওয়াচলিস্ট থেকে সরান',
      like: 'পছন্দ',
      unlike: 'অপছন্দ',
      rate: 'রেট দিন',
      writeReview: 'রিভিউ লিখুন',
      editReview: 'রিভিউ সম্পাদনা',
      deleteReview: 'রিভিউ মুছুন',
      yourRating: 'আপনার রেটিং',
      averageRating: 'গড় রেটিং',
      reviews: 'রিভিউ',
      similarMovies: 'একই ধরণের সিনেমা',
      cast: 'অভিনয়শিল্পী',
      genres: 'ধরণ',
      runtime: 'সময়কাল',
      year: 'সাল',
      trailer: 'ট্রেইলার',
      play: 'চালান',
      pause: 'বিরতি',
      fullscreen: 'পূর্ণ স্ক্রিন',
      skipForward: 'সামনে যান',
      skipBackward: 'পিছনে যান',
      pictureInPicture: 'পিকচার-ইন-পিকচার',
      quality: 'মান',
      subtitlesOff: 'সাবটাইটেল বন্ধ',
      auto: 'স্বয়ংক্রিয়'
    },
    hi: {
      appName: 'MUVIMAX',
      watchNow: 'अभी देखें',
      moreInfo: 'अधिक जानकारी',
      continueWatching: 'देखना जारी रखें',
      trendingNow: 'ट्रेंडिंग',
      popularMovies: 'लोकप्रिय फिल्में',
      newReleases: 'नई रिलीज़',
      topRated: 'सर्वाधिक रेटेड',
      recommendedForYou: 'आपके लिए अनुशंसित',
      action: 'एक्शन',
      comedy: 'कॉमेडी',
      drama: 'नाटक',
      horror: 'हॉरर',
      romance: 'रोमांस',
      thriller: 'थ्रिलर',
      animation: 'एनीमेशन',
      sciFi: 'साइ-फाई',
      family: 'पारिवारिक',
      recentlyAdded: 'हाल ही में जोड़ी गई',
      search: 'खोजें',
      profile: 'प्रोफ़ाइल',
      settings: 'सेटिंग्स',
      watchlist: 'वॉचलिस्ट',
      favorites: 'पसंदीदा',
      history: 'इतिहास',
      notifications: 'सूचनाएं',
      loginRequired: 'लॉगिन आवश्यक',
      pleaseLogin: 'जारी रखने के लिए साइन इन करें',
      signIn: 'साइन इन',
      continueAsGuest: 'अतिथि के रूप में जारी रखें',
      noResults: 'कोई परिणाम नहीं मिला',
      trySearch: 'कुछ और खोजें',
      loading: 'लोड हो रहा है...',
      error: 'कुछ गलत हो गया',
      retry: 'पुनः प्रयास करें',
      emptyWatchlist: 'आपकी वॉचलिस्ट खाली है',
      addMovies: 'अपनी वॉचलिस्ट में फिल्में जोड़ना शुरू करें',
      emptyFavorites: 'अभी कोई पसंदीदा नहीं',
      startFavoriting: 'अपनी पसंदीदा फिल्में पसंदीदा में जोड़ें',
      emptyHistory: 'कोई देखने का इतिहास नहीं',
      startWatching: 'इतिहास बनाने के लिए फिल्में देखना शुरू करें',
      emptyNotifications: 'कोई सूचना नहीं',
      checkLater: 'अपडेट के लिए बाद में जांचें',
      darkMode: 'डार्क मोड',
      lightMode: 'लाइट मोड',
      language: 'भाषा',
      video: 'वीडियो',
      data: 'डेटा',
      privacy: 'गोपनीयता',
      account: 'खाता',
      logout: 'लॉगआउट',
      deleteData: 'स्थानीय डेटा हटाएं',
      playbackQuality: 'प्लेबैक गुणवत्ता',
      autoplay: 'ऑटोप्ले',
      subtitles: 'सबटाइटल',
      playbackSpeed: 'प्लेबैक गति',
      dataSaver: 'डेटा सेवर मोड',
      autoQuality: 'स्वचालित वीडियो गुणवत्ता',
      clearWatchHistory: 'देखने का इतिहास साफ़ करें',
      clearSearchHistory: 'खोज इतिहास साफ़ करें',
      clearContinueWatching: 'जारी देखना साफ़ करें',
      privacyPolicy: 'गोपनीयता नीति',
      termsConditions: 'नियम और शर्तें',
      about: 'MUVIMAX के बारे में',
      version: 'संस्करण',
      joinDate: 'शामिल हुए',
      watchTime: 'देखने का समय',
      moviesWatched: 'देखी गई फिल्में',
      favoriteGenres: 'पसंदीदा शैलियाँ',
      totalRatings: 'कुल रेटिंग',
      totalReviews: 'कुल समीक्षाएं',
      watchlistCount: 'वॉचलिस्ट गिनती',
      share: 'शेयर करें',
      addToWatchlist: 'वॉचलिस्ट में जोड़ें',
      removeFromWatchlist: 'वॉचलिस्ट से हटाएं',
      like: 'पसंद करें',
      unlike: 'पसंद न करें',
      rate: 'रेट करें',
      writeReview: 'समीक्षा लिखें',
      editReview: 'समीक्षा संपादित करें',
      deleteReview: 'समीक्षा हटाएं',
      yourRating: 'आपकी रेटिंग',
      averageRating: 'औसत रेटिंग',
      reviews: 'समीक्षाएं',
      similarMovies: 'समान फिल्में',
      cast: 'कलाकार',
      genres: 'शैलियाँ',
      runtime: 'अवधि',
      year: 'वर्ष',
      trailer: 'ट्रेलर',
      play: 'चलाएं',
      pause: 'रोकें',
      fullscreen: 'पूर्ण स्क्रीन',
      skipForward: 'आगे बढ़ें',
      skipBackward: 'पीछे जाएं',
      pictureInPicture: 'पिक्चर-इन-पिक्चर',
      quality: 'गुणवत्ता',
      subtitlesOff: 'सबटाइटल बंद',
      auto: 'स्वचालित'
    }
  };

  const t = (key) => {
    return translations[language]?.[key] || key;
  };

  const value = {
    language,
    setLanguage,
    t,
    supportedLanguages: [
      { code: 'en', name: 'English' },
      { code: 'bn', name: 'বাংলা' },
      { code: 'hi', name: 'हिन्दी' }
    ]
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};
